# Generated by Django 4.2.24 on 2025-12-14 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_admission_date_alter_student_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.ImageField(max_length=10, null=True, unique=True, upload_to='', validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
