# Generated by Django 4.2.24 on 2025-12-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='class_teacher_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='mark_sheet',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Account_Number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Account_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Bank_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Basic_salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Blood_group',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Branch_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Contract_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Date_of_joining',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Epf_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Father_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='IFSC_code',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Joining_Letter',
            field=models.FileField(null=True, upload_to='Letter/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Language_Known',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Marital_Status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Mother_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Pickup_point',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Qualification',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Resume',
            field=models.FileField(null=True, upload_to='Resume/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Role',
            field=models.CharField(choices=[('teacher', 'teacher'), ('Accountant', 'Accountant'), ('Librarian', 'Librarian')], max_length=209, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Route',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Use_School_bus',
            field=models.CharField(choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Vechicle_Number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Work_Experience',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='second_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_image',
            field=models.ImageField(null=True, upload_to='teacher_image/'),
        ),
    ]
