# Generated by Django 4.2.26 on 2025-11-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_photo', models.ImageField(blank=True, null=True, upload_to='parents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
