# Generated by Django 4.2.26 on 2025-11-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='parent_photo',
        ),
        migrations.AddField(
            model_name='parent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='parent_photos/'),
        ),
    ]
