# Generated by Django 4.2.24 on 2025-12-02 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_parent_contact_number_parent_email_and_more'),
        ('authentication', '0002_remove_parent_parent_photo_parent_photo'),
    ]

    operations = [
    ]
