# Generated by Django 4.2.24 on 2025-12-02 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_merge_20251202_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='photo',
        ),
    ]
