# Generated by Django 4.2.24 on 2025-12-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_parent_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
