# Generated by Django 4.2.24 on 2025-12-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_parent_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='parent_address',
            field=models.TextField(null=True),
        ),
    ]
